# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[
                    ('super_admin', 'Super Admin'),
                    ('manager', 'Manager'),
                    ('inventory', 'Inventory Staff'),
                    ('sales', 'Sales Staff'),
                ],
                default='inventory',
                max_length=20,
            ),
        ),
    ]
